version: '3.8'

services:
  pic-tool:
    build: .
    image: pic-tool:latest
    container_name: pic-tool-container
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - pic_tool_net

networks:
  pic_tool_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.215.0/24
